---
title: Applies Cutor' Network Settings
description: Applies Cutor' optimised network settings
actions:
  - !cmd:
    command: '"CutorDesktop\8. Troubleshooting\Network\Reset Network to Cutor Default.cmd" /silent'
    exeDir: true
    wait: true
